# Generated by Django 3.1.7 on 2021-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
