# Generated by Django 3.1.7 on 2021-12-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20211208_0815'),
        ('teams', '0002_teamfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.setting'),
        ),
    ]
