# Generated by Django 3.1.7 on 2021-12-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='settings',
            new_name='setting',
        ),
    ]
