# Generated by Django 3.1.7 on 2021-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20211208_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
