# Generated by Django 3.1.7 on 2021-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20211210_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tid',
            field=models.BigIntegerField(null=True),
        ),
    ]
