# Generated by Django 3.1.7 on 2021-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_text1', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_text2', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_text3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
