# Generated by Django 3.1.7 on 2021-12-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamfilter'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
