# Generated by Django 3.1.7 on 2021-12-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.URLField(max_length=255, null=True)),
                ('task_id', models.BigIntegerField()),
                ('task_status', models.BooleanField(default=False)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_count', models.CharField(blank=True, max_length=255, null=True)),
                ('task_kind', models.CharField(blank=True, max_length=255, null=True)),
                ('task_price', models.IntegerField(blank=True, null=True)),
                ('task_total_price', models.IntegerField(blank=True, null=True)),
                ('task_over', models.BooleanField(default=False)),
                ('task_invoice_date', models.DateField(null=True)),
                ('task_due_date', models.CharField(blank=True, max_length=255, null=True)),
                ('task_completed_at', models.CharField(blank=True, max_length=255, null=True)),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['task_invoice_date'],
            },
        ),
    ]
