# Generated by Django 3.1.7 on 2021-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_modified_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
