# Generated by Django 3.1.7 on 2021-12-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
